name: MobNegotiation
version: 1.0
author: Zazsona
main: com.zazsona.mobnegotiation.MobNegotiationPlugin
api-version: 1.17
softdepend: [Vault]
commands:
  __negotiation_response__:
    description: Used for internal logic.
permissions:
  mobnegotiation.*:
    description: Allow all enabled negotiation actions
    default: true
    children:
      mobnegotiation.power: true
      mobnegotiation.money: true
      mobnegotiation.items: true
      mobnegotiation.attack: true
  mobnegotiation.power:
    description: Allow the player to negotiate powers
    default: true
  mobnegotiation.money:
    description: Allow the player to negotiate for money
    default: true
  mobnegotiation.items:
    description: Allow the player to negotiate for items
    default: true
  mobnegotiation.attack:
    description: Allow the player to use ALl out Attack
    default: true