-- Sourced from: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/entity/EntityType.java
-- Up to date as of MC 1.21.1

INSERT INTO EntityType (EntityTypeId, Name             )
VALUES                 (0,           'elder_guardian'  )
                      ,(1,           'wither_skeleton' )
                      ,(2,           'stray'           )
                      ,(3,           'husk'            )
                      ,(4,           'zombie_villager' )
                      ,(5,           'skeleton_horse'  )
                      ,(6,           'zombie_horse'    )
                      ,(7,           'donkey'          )
                      ,(8,           'mule'            )
                      ,(9,           'evoker'          )
                      ,(10,          'vex'             )
                      ,(11,          'vindicator'      )
                      ,(12,          'illusioner'      )
                      ,(13,          'creeper'         )
                      ,(14,          'skeleton'        )
                      ,(15,          'spider'          )
                      ,(16,          'giant'           )
                      ,(17,          'zombie'          )
                      ,(18,          'slime'           )
                      ,(19,          'ghast'           )
                      ,(20,          'zombified_piglin')
                      ,(21,          'enderman'        )
                      ,(22,          'cave_spider'     )
                      ,(23,          'silverfish'      )
                      ,(24,          'blaze'           )
                      ,(25,          'magma_cube'      )
                      ,(26,          'ender_dragon'    )
                      ,(27,          'wither'          )
                      ,(28,          'bat'             )
                      ,(29,          'witch'           )
                      ,(30,          'endermite'       )
                      ,(31,          'guardian'        )
                      ,(32,          'shulker'         )
                      ,(33,          'pig'             )
                      ,(34,          'sheep'           )
                      ,(35,          'cow'             )
                      ,(36,          'chicken'         )
                      ,(37,          'squid'           )
                      ,(38,          'wolf'            )
                      ,(39,          'mooshroom'       )
                      ,(40,          'snow_golem'      )
                      ,(41,          'ocelot'          )
                      ,(42,          'iron_golem'      )
                      ,(43,          'horse'           )
                      ,(44,          'rabbit'          )
                      ,(45,          'polar_bear'      )
                      ,(46,          'llama'           )
                      ,(47,          'parrot'          )
                      ,(48,          'villager'        )
                      ,(49,          'turtle'          )
                      ,(50,          'phantom'         )
                      ,(51,          'cod'             )
                      ,(52,          'salmon'          )
                      ,(53,          'pufferfish'      )
                      ,(54,          'tropical_fish'   )
                      ,(55,          'drowned'         )
                      ,(56,          'dolphin'         )
                      ,(57,          'cat'             )
                      ,(58,          'panda'           )
                      ,(59,          'pillager'        )
                      ,(60,          'ravager'         )
                      ,(61,          'trader_llama'    )
                      ,(62,          'wandering_trader')
                      ,(63,          'fox'             )
                      ,(64,          'bee'             )
                      ,(65,          'hoglin'          )
                      ,(66,          'piglin'          )
                      ,(67,          'strider'         )
                      ,(68,          'zoglin'          )
                      ,(69,          'piglin_brute'    )
                      ,(70,          'axolotl'         )
                      ,(71,          'glow_squid'      )
                      ,(72,          'goat'            )
                      ,(73,          'allay'           )
                      ,(74,          'frog'            )
                      ,(75,          'tadpole'         )
                      ,(76,          'warden'          )
                      ,(77,          'camel'           )
                      ,(78,          'sniffer'         )
                      ,(79,          'armadillo'       )
                      ,(80,          'bogged'          )
;