INSERT INTO TextContent (TextContentId, BaseLanguageCode, BaseText)
VALUES
       (1100, 'en', 'YoU waNtiN'' mY poWeR jus'' liKe tHat? YoU''lL hAve tO woo mE fIrsT!')
           ,(1101, 'en', 'Hand it over.')
               ,(1102, 'en', 'AlrIghT, aLrigHt, I gEt iT.')
               ,(1103, 'en', 'Ah...')
               ,(1104, 'en', 'YoU doN''t bEaT aRouNd tHe buSh, hUh?')
               ,(1105, 'en', 'MaYbE...')

               ,(1106, 'en', 'NAH''!')
               ,(1107, 'en', 'CaN''T!')
               ,(1108, 'en', 'TaKe a HiKe!')
               ,(1109, 'en', 'CaN''T be BotHerEd!')
           ,(1110, 'en', 'I''m no good at that.')
               ,(1111, 'en', 'Ha! YoU loOk iT!')
               ,(1112, 'en', 'YoU aNd mE bOtH...')
               ,(1113, 'en', 'So mUcH fOr cHivAlrY.')
               ,(1114, 'en', 'Me NeiThEr.')

               ,(1115, 'en', 'SHaMe!')
               ,(1116, 'en', 'Oh... gUeSs we''lL hAvE tO fIghT tHen.')
               ,(1117, 'en', 'SoUndS lIkE yOu jUs'' cAn''T be BotHerEd!')
               ,(1118, 'en', 'Oh, yOu jUs'' doN''t LiKe mE!')
           ,(1119, 'en', 'How about my place next Saturday? <3')
               ,(1120, 'en', 'I''lL bRiNg tHiS siCk boDy.')
               ,(1121, 'en', 'Oh! Su- SuRe... HaHa, jUs'' joKin''!')
               ,(1122, 'en', '... THat''S a jOke, rIghT?')
               ,(1123, 'en', 'I mIghT be BuSy...')

               ,(1124, 'en', 'YoU''Re juS'' nOt my tYpe!')
               ,(1125, 'en', 'SoRrY, yoU''rE nOt reAllY my tyPe...')
               ,(1126, 'en', 'No chAncE, sQuiShy gUy.')
               ,(1127, 'en', 'DoN''t paTronIse Me.')
      ,(1128, 'en', 'C''mOn thOugh. WHat''S yoUr tYpe?')
          ,(1129, 'en', 'Oh, you know...')
               ,(1130, 'en', 'HeH, oHhHhhHhh. I sEe.')
               ,(1131, 'en', 'YeAh...')
               ,(1132, 'en', 'ProBaBlY.')
               ,(1133, 'en', 'YeaH... GuesS I dO...')

               ,(1134, 'en', 'WhaT? SlImeS? SilVerFisH? If yoU''rE noT spIttIng it oUt, I''lL spiT it OutTa yoU!')
               ,(1135, 'en', 'NoT reaLly...')
               ,(1136, 'en', 'NoPe!')
               ,(1137, 'en', 'I doN''t kNoW noThiN''.')
          ,(1138, 'en', 'Slimes.')
               ,(1139, 'en', 'Ha! GoOd oNe!')
               ,(1140, 'en', 'YoU''rE braVe tO aDmiT thAt...')
               ,(1141, 'en', 'To eAcH theIr oWn.')
               ,(1142, 'en', '... AlrIghT.')

               ,(1143, 'en', 'Ha! HaHa! HaHaHaHaHaHa!!!')
               ,(1144, 'en', 'I waS seRioUs...')
               ,(1145, 'en', 'DoN''T piSs mE abOuT.')
               ,(1146, 'en', '...NoT quIte sKelEtoNs, thEn...')
          ,(1147, 'en', 'Fire Type, it''s strong against Grass.')
               ,(1148, 'en', 'GoOd pIck!')
               ,(1149, 'en', 'HeY, me Too!')
               ,(1150, 'en', 'NoT quIte whAt I meAnt, bUt suRe.')
               ,(1151, 'en', 'YeAh, I gueSs...')

               ,(1152, 'en', 'Ah, I sEe yoU''re jUsT a lOneR!')
               ,(1153, 'en', 'ArE yoU mOckIng mE?')
               ,(1154, 'en', 'YoU idIoT.')
               ,(1155, 'en', 'UghhhHhhhHhh...')
      ,(1156, 'en', 'C''mOn thOugh, iF yOu caN''t wOo mE I knOw all sOrts of gOod loOkerS I cAn intRoduCe yoU to!')
           ,(1157, 'en', 'I''m not interested.')
               ,(1158, 'en', 'THat''s tHe spIriT!')
               ,(1159, 'en', 'HeH... FaIr enOugh.')
               ,(1160, 'en', 'YoU''vE gOt cOnviCtiOn, I sEe.')
               ,(1161, 'en', 'NeitHeR, reAllY...')

               ,(1162, 'en', 'BiT of A sqUarE, arEn''t yOu?')
               ,(1163, 'en', 'AlRighT, tHen. I wAs Just tRyiN'' to Be nIce.')
               ,(1164, 'en', 'ThEn wE havE ouRselVes nO furTher buSinesS.')
               ,(1165, 'en', 'WhAteVer...')
           ,(1166, 'en', 'You''re trying way too hard.')
               ,(1167, 'en', 'AheHeh. MaYbe. ThIs pIle of BonEs cAn''t kEeP uP wIth wHat thE liViNg WanT.')
               ,(1168, 'en', 'YoU thInK sO?')
               ,(1169, 'en', 'DoN''t We aLl?')
               ,(1170, 'en', 'ThAt''S a nEw oNe fOr me, hEh...')

               ,(1171, 'en', 'WhAt? YoU doN''t tHinK I got wHat I''m pRomIsiN''?')
               ,(1172, 'en', 'Oh... OkAy...')
               ,(1173, 'en', 'I''lL shOw yoU tRying hArd!')
               ,(1174, 'en', 'NoT eVen mY beSt iS eNouGh... lEt''s eNd thIs.')
           ,(1175, 'en', 'Yes! Let''s go!')
               ,(1176, 'en', 'YoU''rE aS fuN as yOu aRe gUllIble. HaHa!')
               ,(1177, 'en', 'YoU''rE rEallY inTereSted iN my fRienDs?')
               ,(1178, 'en', 'At LeasT I kNow yOu tRust Me, eVen if yOur hEad iS empTy.')
               ,(1179, 'en', 'Ha... ThaT woUld be tHe dReaM.')

               ,(1180, 'en', 'HaHaaaa! I gOt yoU gOod. NoW let''S rEalLy plAy.')
               ,(1181, 'en', 'Oh... Uh I dOn''T acTualLy hAvE anYonE... SoRrY.')
               ,(1182, 'en', 'YoU FOoL!')
               ,(1183, 'en', 'Ugh... YOu arE DenSe.')







      ,(1184, 'en', 'I''lL neEd sOmE lunCh firSt. Can wE taKe a bReaK anD go eAt soMethIng?')
           ,(1185, 'en', 'I''m not hungry.')
               ,(1186, 'en', 'YoU beEn snacKing? C''moN, let''S tHinK abOuT thIs.')
               ,(1187, 'en', 'CaN We gO gEt soMethiNg foR mE aT leaSt?')
               ,(1188, 'en', 'We''Ll gEt soMe jUst fOr mE, thEn...')
               ,(1189, 'en', 'GuEsS it''lL be a tAble fOr oNe...')

               ,(1190, 'en', 'WeLl, I''lL mAke it A taBle foR onE, thEn!')
               ,(1191, 'en', 'Oh... OkAy...')
               ,(1192, 'en', 'FiNe, thEn.')
               ,(1193, 'en', 'I''lL kilL mY oWn foOd thEn.')
           ,(1194, 'en', 'Only if we split the foraging.')
               ,(1195, 'en', 'SuRe, 70/30!')
               ,(1196, 'en', 'AlRigHt, sOunDs faIr!')
               ,(1197, 'en', 'WoRks fOr mE.')
               ,(1198, 'en', 'NoThiN'' coMes fRee, I guEss.')

               ,(1199, 'en', 'Or I CoUlD splIt yoU!')
               ,(1200, 'en', 'Oh... nO thanKs.')
               ,(1201, 'en', 'YoU cAn''T spRinG thAt oN me nOw!')
               ,(1202, 'en', 'I thOughT it''D be oN yoU...')
           ,(1203, 'en', 'Let''s grab something.')
               ,(1204, 'en', 'I''lL tAke aNythIn'!')
               ,(1205, 'en', 'I''m nOt fUsSy!')
               ,(1206, 'en', 'Now wE''rE geTtinG soMewheRe.')
               ,(1207, 'en', 'SuRe...')

               ,(1208, 'en', 'I''lL gRab yoUr flEsh!')
               ,(1209, 'en', 'I thOughT you''D haVe soMethIng...')
               ,(1210, 'en', 'GiVe me WhaT yoU haVe iNstEaD.')
               ,(1211, 'en', 'Ugh... CaN''t be BothEred. GivE me yoUrs.')
      ,(1212, 'en', 'AlrIghT, whAt dO yoU wAnt tO eaT, thEn?')
           ,(1213, 'en', 'Anything.')
               ,(1214, 'en', 'HeH, hoW abOut soMe miLk? CalCium''s gOod foR thEse bOnes!')
               ,(1215, 'en', 'If yoU sAy sO...')
               ,(1216, 'en', 'I''lL picK thEn. I wAs thInKinG aboUt sOmE pIe.')
               ,(1217, 'en', 'YeAh, I''d eAt diRt.')

               ,(1218, 'en', 'I fiGurE yoU''ll Do NiceLy.')
               ,(1219, 'en', 'I thOughT you hAd a pLaN...')
               ,(1220, 'en', 'ShouLda piCked soMethin'', fleShbaG.')
               ,(1221, 'en', 'ArE yoU eVen stIll IntErestEd?')
           ,(1222, 'en', 'I''ve got this dirt block...')
               ,(1223, 'en', 'SouNds scRummY!')
               ,(1224, 'en', 'GuEsS it''lL do...')
               ,(1225, 'en', 'UgH, foOd''s fooD.')
               ,(1226, 'en', 'It''S jUst tHe soRt of thIng I''m Worth...')

               ,(1227, 'en', 'HaHa, I coUld dO betTer thAn thAt!')
               ,(1228, 'en', 'Oh... I wAs expeCtin'' SomethiNg bettEr.')
               ,(1229, 'en', 'YoU caN do BetTer thAn thAt.')
               ,(1230, 'en', 'ThAt''s nOt woRth eaTing...')
           ,(1231, 'en', 'Cake.')
               ,(1232, 'en', 'NoW we''Re talKin''. It''S a PartY!')
               ,(1233, 'en', 'ThAt''d be Nice...')
               ,(1234, 'en', 'ThEn it''S setTleD!')
               ,(1235, 'en', 'YeaH, soUnds gOod...')

               ,(1236, 'en', 'I RecKon I''lL kiLl you For aN eXtra slIce!')
               ,(1237, 'en', 'I... doN''t lIke caKe.')
               ,(1238, 'en', 'YoU haVe no CultUre, skinBod.')
               ,(1239, 'en', 'ARe yoU tryIn'' to Make thIs a paRty? No thAnks.')
      ,(1240, 'en', 'LeT''s plAy a gaMe then, gueSs what I wAnnA eat!')
           ,(1241, 'en', 'You don''t look like you can eat...')
               ,(1242, 'en', 'FaIr poInT!')
               ,(1243, 'en', 'YeAh, thanKs foR notiCin'.')
               ,(1244, 'en', 'AlriGht, EinSteiN. Well pLayed.')
               ,(1245, 'en', 'I uSed tO, thOugh. JuSt liKe yoU.')

               ,(1246, 'en', 'ThAt''s nOt hOw you Play thE game!')
               ,(1247, 'en', 'ThAnkS foR poIntIng it oUt mE...')
               ,(1248, 'en', 'DUH!')
               ,(1249, 'en', 'I kNow...')
           ,(1250, 'en', 'Something high in calcium.')
               ,(1251, 'en', 'AwhhHhhh yIsssSsss.')
               ,(1252, 'en', 'YEah, I gueSs so...')
               ,(1253, 'en', 'That''D do Me weLl.')
               ,(1254, 'en', 'MiGht lIft my SpritS...')

               ,(1255, 'en', 'YuP! YoU ouGht To do!')
               ,(1256, 'en', 'Is thAt suPposeD to be A joke?')
               ,(1257, 'en', 'No.')
               ,(1258, 'en', 'UgghHhhHhh. DoN''t BorE me wiTh thAt oNe.')
           ,(1259, 'en', 'Shut up.')
               ,(1260, 'en', 'NoW thAt''s a sPicY rEsponSe!')
               ,(1261, 'en', 'Oh... SoRrY! JuSt wAntEd a bIt oF fUn, bUt I gEt iT...')
               ,(1262, 'en', 'HeH, wAnnA geT tO tHe pOinT, hUh?')
               ,(1263, 'en', 'PrEfEr a Bit oF siLenCe toO, hUh?')

               ,(1264, 'en', 'AwhHh. YoU''rE noT as Fun as I thOughT you''D be.')
               ,(1265, 'en', 'FiNe...')
               ,(1266, 'en', 'DoN''t giVe me thAt lip!')
               ,(1267, 'en', 'YoU''rE toO cockY.')







      ,(1268, 'en', 'You wAnt to taKe from Me whIle I''m DowN? DoEs that nOt boTher YouR coNsciEnce?')
           ,(1269, 'en', 'Now that you mention it...')
               ,(1270, 'en', 'YoU cErtaInly loOk boThereD!')
               ,(1271, 'en', 'YeaH...')
               ,(1272, 'en', 'YoU shOulD thInk tHingS thrOugh in fUture.')
               ,(1273, 'en', 'We''rE all JusT miStakeS liKe thAt...')

               ,(1274, 'en', 'GooD thiNg I don''t hAve a ConscienCe!')
               ,(1275, 'en', 'TimE to... FLEE!')
               ,(1276, 'en', 'ShouLda thoUght abouT it bEfore, bagGybraIns.')
               ,(1277, 'en', 'YoU don''T evEn know...')
           ,(1278, 'en', '...Nope')
               ,(1279, 'en', 'DoN''t thInK iT''d Much boTher mIne eiTher.')
               ,(1280, 'en', 'At leAst yOu''rE hoNest...')
               ,(1281, 'en', 'At leAst yOu''rE hoNest.')
               ,(1282, 'en', 'ShoUlda eXpecTed aS muCh...')

               ,(1283, 'en', 'GoOd. ThIs woN''t wEigh oN mIne.')
               ,(1284, 'en', 'YoU... You''Re moRe hEartLesS thAn mE! And I doN''t eVen haVe oNe no mOrE!')
               ,(1285, 'en', 'YoU neEd tEacHinG a lEssOn!')
               ,(1286, 'en', 'Oh... RiGht...')
           ,(1287, 'en', 'It needs to be done.')
               ,(1288, 'en', 'YeAh, yeaH. WhatEver.')
               ,(1289, 'en', 'YoU... thInk So?')
               ,(1290, 'en', 'SuPpose we aLl haVe ouR tiMe...')
               ,(1291, 'en', 'I KnoW...')

               ,(1292, 'en', 'I doN''t tHinK sO!')
               ,(1293, 'en', 'I''m nOt reAdy! NoT yeT!')
               ,(1294, 'en', 'YoU''rE riGht. TiMe to End yOu.')
               ,(1295, 'en', 'I dOn''T caRe muCh for YouR naRratiVe.')
      ,(1296, 'en', 'ThiS couLda bEen the OthEr waY arOunD, y''kNow?')
           ,(1297, 'en', 'No chance.')
               ,(1298, 'en', 'I''m LikiN'' The MacHo aCt!')
               ,(1299, 'en', 'I GueSs So, I''vE nOt goT the SkilLs I uSed tO.')
               ,(1300, 'en', 'AlrIghT, alRighT.')
               ,(1301, 'en', 'YoU''rE riGht...')

               ,(1302, 'en', 'We''Ll seE aboUt thAt!')
               ,(1303, 'en', 'NaH'', I wOn''T falL thAt eaSily.')
               ,(1304, 'en', 'I diSagRee.')
               ,(1305, 'en', 'ThEn whY bOthEr TalkIng...?')
           ,(1306, 'en', 'Want to swap?')
               ,(1307, 'en', 'AhhHhh. ThE ol'' SwitCheroO! YoU keEp thIngs YouR waY, for thIs tiMe.')
               ,(1308, 'en', 'YeAh... It''S oKay thOugh, yoU eaRneD thIs...')
               ,(1309, 'en', 'We''Re toO faR in nOw, buT thanKs.')
               ,(1310, 'en', 'TheRe''d bE nO poiNt noW...')

               ,(1311, 'en', 'YoU kiDdin''? I gOt the BesT angLe to kNock yoU doWn frOm heRe!')
               ,(1312, 'en', 'DoN''t TeaSe me...')
               ,(1313, 'en', 'DoN''t patRonise Me.')
               ,(1314, 'en', 'WhaT''d bE the pOint!?')
           ,(1315, 'en', 'Yet here we are.')
               ,(1316, 'en', 'YeAh, YeaH. I gEt it.')
               ,(1317, 'en', '...SupPose thIs is wHat faTe had iN stoRe...')
               ,(1318, 'en', 'GoT tO deAl with It nOw thEn.')
               ,(1319, 'en', 'ThAt''s jUst thE waY of tHe caRds...')

               ,(1320, 'en', 'LeT''s chAnge thAt arOund!')
               ,(1321, 'en', 'I... I''lL fiGht it!')
               ,(1322, 'en', 'NoT foR loNg.')
               ,(1323, 'en', 'FaTe haS someThing elSe in sTore for Us botH.')
      ,(1324, 'en', 'JuSt leT me teLl you, I Am nOt the oNe yoU shoUld detEst.')
           ,(1325, 'en', 'You''re right.')
               ,(1326, 'en', 'YeAh, yOu knOw it. I''m aLwaYs rIgHt.')
               ,(1327, 'en', 'ThAnkS foR reAliSin'.')
               ,(1328, 'en', 'NoW you gEt it.')
               ,(1329, 'en', 'ThEre are bEingS thAt CeRtaiNly gEt a Lot Worse thAn me...')

               ,(1330, 'en', 'ThAnkIn'' yOu, I thInk my HatRed oF yoUr muG iS weLl pLacEd, thOugh!')
               ,(1331, 'en', '...')
               ,(1332, 'en', 'ShOuLda picKed up on ThAt frOm thE stArt.')
               ,(1333, 'en', 'BuT stIll, I wiSh fOr yoU to End mE.')
           ,(1334, 'en', 'That''s absurd.')
               ,(1335, 'en', 'NiCe to See eVen the New kiDs on tHe blOck kEep up wIth tHe pRejuDice.')
               ,(1336, 'en', '...')
               ,(1337, 'en', 'LeT uS deTesT eaCh otHer eqUallY, thEn.')
               ,(1338, 'en', 'LoOks liKe thAt''s tHe way It''S goTta be, huH?')

               ,(1339, 'en', 'JuSt liKe yoUr chAnces of tAkinG me dOwn!')
               ,(1340, 'en', 'Oh, RigHt...')
               ,(1341, 'en', 'YeAh, it Is. I juSt wAnted yoU to sHut uP for a Bit!')
               ,(1342, 'en', 'GuEss thEre''ll nEvEr be pEacE. Let''S enD thiS.')
           ,(1343, 'en', 'I''ll be the judge of that.')
               ,(1344, 'en', 'AlriGht, I''lL tAke thAt rolL of The DiCe.')
               ,(1345, 'en', 'I''lL leT yoU arrIve at yoUr oWn decSionS, thEn...')
               ,(1346, 'en', 'FiNe, jUst doN''t MeSs me abOut.')
               ,(1347, 'en', 'No neEd to suGar coAt it...')

               ,(1348, 'en', 'I aiN''t gOnnA waIt all Day foR yoU to mAke uP yoUr miNd.')
               ,(1349, 'en', 'I doN''t thInk I cAn taKe noT knOwing...')
               ,(1350, 'en', 'I doN''t tAke wEll tO suCh amBiguity.')
               ,(1351, 'en', 'SoMetiMes it Pays to jUst comMit to hAtred, yoU knOw?')



      ,(1352, 'en', 'I geTchA nOw. HeRe, thIs %POWER% poWeR''s yOuRs.')
      ,(1353, 'en', 'YoU kNoW wHaT I feEl... HeRe, hAve a %POWER% pOwEr.')
      ,(1354, 'en', 'EnOugH oF thAt thoUgh, tHiS %POWER% PoWeR''s YoUrs fOr tHe taKin''.')
      ,(1355, 'en', 'ThAnkS foR heAriN'' mE out, uSe thIs %POWER% power bEtTer thaN I dId.')
;