INSERT INTO TextContent (TextContentId, BaseLanguageCode, BaseText)
VALUES
       (1700, 'en', 'You want... Power? First tell me... what you want do... with life?')
           ,(1701, 'en', 'Achieve my dreams.')
               ,(1702, 'en', 'I try... Not succeed... Fun ride though...')
               ,(1703, 'en', 'Wish... you luck.')
               ,(1704, 'en', 'Gurgh... Good luck... You need it.')
               ,(1705, 'en', 'Bugh... I... once... had dreams.')

               ,(1706, 'en', 'Hargh! You... make me laugh...')
               ,(1707, 'en', 'Guhhh... Why... have? Never succeed...')
               ,(1708, 'en', 'Grah! You... waste time.')
               ,(1709, 'en', 'No one... Buh... have dreams.')
           ,(1710, 'en', 'Help everyone I meet.')
               ,(1711, 'en', 'Help...? Hah! You hit me... Funny.')
               ,(1712, 'en', 'You... Ugh... nicer than me.')
               ,(1713, 'en', 'Brr... You... spend life... well.')
               ,(1714, 'en', 'Gurgh... Good... for living...')

               ,(1715, 'en', 'Hruh. What... waste. Let have... fun.')
               ,(1716, 'en', 'Me... not compare. Hurgh...')
               ,(1717, 'en', 'Lie.')
               ,(1718, 'en', 'Why... bother? Guh...')
           ,(1719, 'en', 'Die.')
               ,(1720, 'en', 'Hrah! Join... me. Much fun.')
               ,(1721, 'en', 'Like... Gu... me.')
               ,(1722, 'en', 'Hmuh... I... see.')
               ,(1723, 'en', 'I... same desire.')

               ,(1724, 'en', 'Let... me help. Hraugh!')
               ,(1725, 'en', 'Guh... That''s... sad. Life good.')
               ,(1726, 'en', 'That... waste. Kruh...')
               ,(1727, 'en', 'Guh... Afterlife... bad. Me show you.')
      ,(1728, 'en', 'Surgh... So... what like... to still have freedom... to choose what do with life?')
          ,(1729, 'en', 'I cherish it.')
               ,(1730, 'en', 'Hurh... In afterlife... I don''t have... to bother.')
               ,(1731, 'en', 'Ourgh... Once did... too.')
               ,(1732, 'en', 'Guh... Good.')
               ,(1733, 'en', 'Gruh... Better... times.')

               ,(1734, 'en', 'Hargh... Afterlife... easier... You see... Now.')
               ,(1735, 'en', 'Guh... No... brag.')
               ,(1736, 'en', '...Why?')
               ,(1737, 'en', 'Burgh... Forget... cherish.')
          ,(1738, 'en', 'It defines me.')
               ,(1739, 'en', 'You... sound like dictionary.')
               ,(1740, 'en', 'Defines... huurrr...')
               ,(1741, 'en', 'Buh... You... straightforward. Like me.')
               ,(1742, 'en', 'Wish... have... choice again... Guh...')

               ,(1743, 'en', 'Death... define you. Hargh!')
               ,(1744, 'en', 'Have no... definition... I take yours.')
               ,(1745, 'en', 'Bad... answer. Gurgh!')
               ,(1746, 'en', 'Burgh... So simple... not define life.')
          ,(1747, 'en', 'It''s everything.')
               ,(1748, 'en', 'Hurgh... If... say so.')
               ,(1749, 'en', 'Hmm...')
               ,(1750, 'en', 'Guh... Maybe.')
               ,(1751, 'en', 'Buh... You... understand... life.')

               ,(1752, 'en', 'Guh... Lighten up.')
               ,(1753, 'en', 'Buh... I... have nothing... then.')
               ,(1754, 'en', 'Argh... Want answer... not lyrics.')
               ,(1755, 'en', 'Guh... Me... nothing.')
      ,(1756, 'en', 'Buh... So... what... I do with... afterlife?')
           ,(1757, 'en', 'Join me.')
               ,(1758, 'en', 'Hurgh? Thanks... But... you... smell funny.')
               ,(1759, 'en', 'Burgh? Want... me? Can''t accept... but thanks.')
               ,(1760, 'en', 'Not for me... Ugh... but thanks.')
               ,(1761, 'en', 'Gurr... Thanks... but I slow you down...')

               ,(1762, 'en', 'Hurgh. You... ruin my... street cred.')
               ,(1763, 'en', 'Me... too slow.')
               ,(1764, 'en', 'Burgh... No time... for you.')
               ,(1765, 'en', 'Urgh... Too much... effort.')
           ,(1766, 'en', 'PARTAAAAY!')
               ,(1767, 'en', 'I... can... gruh... GROOVE!')
               ,(1768, 'en', 'Sound... fun... Thanks.')
               ,(1769, 'en', 'Guh... Time... to... lighten up.')
               ,(1770, 'en', 'Buh... I... just watch.')

               ,(1771, 'en', 'Hargh... Not... with you.')
               ,(1772, 'en', 'Not... for me.')
               ,(1773, 'en', 'Buh... You... irritating.')
               ,(1774, 'en', 'Gruh... Joy... Sickening.')
           ,(1775, 'en', 'Follow your fate.')
               ,(1776, 'en', 'A fate... for fun. Burguhuh.')
               ,(1777, 'en', 'Will... do.')
               ,(1778, 'en', '...Not easy...')
               ,(1779, 'en', 'Gruh... Easy... for some.')

               ,(1780, 'en', 'Nurgh... Not... my style.')
               ,(1781, 'en', 'Ugghhh... Fate... is lost.')
               ,(1782, 'en', 'Burghhh... No... such thing.')
               ,(1783, 'en', 'My fate... is to hate...')






      ,(1784, 'en', 'Purgh... Power? How about... propose marriage... first?')
           ,(1785, 'en', 'Eww, no.')
               ,(1786, 'en', 'Pargh. I see... I out of... your league.')
               ,(1787, 'en', 'Guh... I... wouldn''t either.')
               ,(1788, 'en', 'Hargh. Saves... divorce papers.')
               ,(1789, 'en', 'Gruh... Good... choice.')

               ,(1790, 'en', 'Till... death... do us part. Hragh!')
               ,(1791, 'en', 'Graugh... You... awful.')
               ,(1792, 'en', 'We... no business... then.')
               ,(1793, 'en', 'Urgh... You kick... while I down.')
           ,(1794, 'en', 'You read my mind.')
               ,(1795, 'en', 'Harr... I''ll... set a date.')
               ,(1796, 'en', 'I know... juhhh... joke... But thanks.')
               ,(1797, 'en', 'Burr... It... only fair.')
               ,(1798, 'en', 'Buh... No... mind read...')

               ,(1799, 'en', 'Well... hurgh... I... refuse.')
               ,(1800, 'en', 'Not... true proposal.')
               ,(1801, 'en', 'You... immature.')
               ,(1802, 'en', 'I... not ready... yet.')
           ,(1803, 'en', 'I don''t believe in marriage.')
               ,(1804, 'en', 'You just believe... Santa Claus?')
               ,(1805, 'en', 'Buh... Me... neither.')
               ,(1806, 'en', 'Hurgh... Good.')
               ,(1807, 'en', 'Hurh... Neither... I.')

               ,(1808, 'en', '...Shame. We... funny children.')
               ,(1809, 'en', 'Oh...')
               ,(1810, 'en', 'Furgh... Fool.')
               ,(1811, 'en', 'Ugh... It... only... wish.')
      ,(1812, 'en', 'Either... way. Should confess... sins... now.')
           ,(1813, 'en', 'No chance.')
               ,(1814, 'en', 'Huhhh... Yeah... same.')
               ,(1815, 'en', 'Bugh... Keep... to grave. Smart.')
               ,(1816, 'en', 'Your... truth...')
               ,(1817, 'en', 'I... guh... have secrets... to.')

               ,(1818, 'en', 'No... fun.')
               ,(1819, 'en', 'You... bad... person?')
               ,(1820, 'en', 'No... trust you.')
               ,(1821, 'en', 'You... never find... happiness.')
           ,(1822, 'en', 'I''ve been a good little human.')
               ,(1823, 'en', 'If... you say so...')
               ,(1824, 'en', 'Guhhh... R-really?')
               ,(1825, 'en', 'Understood...')
               ,(1826, 'en', 'Buh... World... better place... if true.')

               ,(1827, 'en', 'I... not so sure.')
               ,(1828, 'en', 'Not... true. I... see.')
               ,(1829, 'en', 'You... lie.')
               ,(1830, 'en', 'I... not... so good.')
           ,(1831, 'en', 'I have a dark past.')
               ,(1832, 'en', 'Bugh! What... worst you do? Forget to... say please?')
               ,(1833, 'en', 'Buh... We all... have history.')
               ,(1834, 'en', 'I... understand.')
               ,(1835, 'en', 'I... same.')

               ,(1836, 'en', 'Ow... the edge.')
               ,(1837, 'en', 'You... bad. Gargh!')
               ,(1838, 'en', 'Guhhhh... Yeah... right.')
               ,(1839, 'en', 'Mine... darker.')
      ,(1840, 'en', 'Come on... what vows... you make?')
           ,(1841, 'en', 'Vows lead to disappointment.')
               ,(1842, 'en', 'Gurhhhh... I... take that... as vow.')
               ,(1843, 'en', 'Thanks... for spare me... sadness.')
               ,(1844, 'en', 'You... right.')
               ,(1845, 'en', 'Always... I... hurt before.')

               ,(1846, 'en', 'Buh... Like... that... answer.')
               ,(1847, 'en', 'You... lack... heart.')
               ,(1848, 'en', 'You... hopeless... disappointment.')
               ,(1849, 'en', 'Buh... You... not care.')
           ,(1850, 'en', 'I''ll cherish you forever.')
               ,(1851, 'en', 'You... make me... blush.')
               ,(1852, 'en', 'Fuhhh.... Thanks.')
               ,(1853, 'en', 'Not... quite feel same... But okay.')
               ,(1854, 'en', 'Appreciate... the idea. I... not lovable.')

               ,(1855, 'en', 'I... cherish killing you.')
               ,(1856, 'en', '...Guh. Don''t... lie.')
               ,(1857, 'en', 'That... impossible... Fool.')
               ,(1858, 'en', 'I... incapable... of love.')
           ,(1859, 'en', 'I vow to kill you.')
               ,(1860, 'en', 'Hargh! You... too weak... Good... joke.')
               ,(1861, 'en', 'I... appreciate... death... later.')
               ,(1862, 'en', 'You... actually commit.')
               ,(1863, 'en', 'End... my suffering... I... remember this.')

               ,(1864, 'en', 'I... kill you... FIRST!')
               ,(1865, 'en', 'Guh... So... be it.')
               ,(1866, 'en', '...Fool.')
               ,(1867, 'en', 'Guh... Go ahead...')






      ,(1868, 'en', 'Power...? Do... I see... hand shaking? You... okay?')
           ,(1869, 'en', 'It''s a bit chilly...')
               ,(1870, 'en', 'That just... because I cool.')
               ,(1871, 'en', 'Brrr... I... cold too.')
               ,(1872, 'en', 'Brrr... Should... layer up.')
               ,(1873, 'en', 'Death... guh... is always... cold.')

               ,(1874, 'en', 'You... wimp.')
               ,(1875, 'en', 'Buh... You just... want leave.')
               ,(1876, 'en', 'No... it not.')
               ,(1877, 'en', 'You... don''t know... cold.')
           ,(1878, 'en', 'I''m just excited to talk!')
               ,(1879, 'en', 'I... am... pretty charismatic.')
               ,(1880, 'en', 'To... Talk... to me?')
               ,(1881, 'en', 'Buh... You... calm down... then.')
               ,(1882, 'en', 'Buh... Don''t... be.')

               ,(1883, 'en', 'I... NOT!')
               ,(1884, 'en', 'I... not worth... excitement.')
               ,(1885, 'en', 'Hurgh... You... childish.')
               ,(1886, 'en', 'I... not mood.')
           ,(1887, 'en', 'Jazz hands!')
               ,(1888, 'en', 'Grrrroovy!')
               ,(1889, 'en', 'You... want dance?')
               ,(1890, 'en', 'Guuhhh... Not... my style... but... must... admit... you good.')
               ,(1891, 'en', 'Nice... save.')

               ,(1892, 'en', 'You... dare challenge... jazz hand master?')
               ,(1893, 'en', 'Buh... I... just wanted... to know... if you... okay.')
               ,(1894, 'en', 'HRUAGH!')
               ,(1895, 'en', 'Graugh... Go... away.')
      ,(1896, 'en', 'You... ever... get shaky... when kid too?')
           ,(1897, 'en', 'When I was scared...')
               ,(1898, 'en', 'Hurh... You... still... scared now!')
               ,(1899, 'en', 'Me... too.')
               ,(1900, 'en', 'You... look scared... now. No try... hide it.')
               ,(1901, 'en', 'Buh... I... scared... lots.')

               ,(1902, 'en', 'Ha-hargh! You... wimp.')
               ,(1903, 'en', 'Buh... You... look scared... of me... now.')
               ,(1904, 'en', 'Gurgh. I... no time... for weak wimp.')
               ,(1905, 'en', 'Wish... scared. I... no feeling.')
           ,(1906, 'en', 'Only after coffee.')
               ,(1907, 'en', 'Ha-hurgh... Bet... you shake... on toilet too.')
               ,(1908, 'en', 'Ourgh... Always... make me... shake.')
               ,(1909, 'en', 'Bugh... I... also... coffee addict. That why... not rest... after death.')
               ,(1910, 'en', 'Ugh... Even child... need coffee... for busy life...')

               ,(1911, 'en', 'Boring... child... have coffee.')
               ,(1912, 'en', 'Baugh! Why... you... have coffee... as kid?')
               ,(1913, 'en', 'Graugh... Child... coffee... bad.')
               ,(1914, 'en', 'Not... joke question.')
           ,(1915, 'en', 'Once...')
               ,(1916, 'en', 'Huhhh... You''d... still shake... now!')
               ,(1917, 'en', 'I... no pry.')
               ,(1918, 'en', 'Buh... Prepare you... Harder time... come yet.')
               ,(1919, 'en', 'Guh... We both... have suffered.')

               ,(1920, 'en', 'I... make that twice... Now.')
               ,(1921, 'en', 'I... don''t... Ugh... believe.')
               ,(1922, 'en', 'Ugh... Weak...')
               ,(1923, 'en', 'You... not suffered enough... like me.')
      ,(1924, 'en', 'Speaking of... shaky... hands... You... any good... at sewing? I... need clothes... fixing.')
           ,(1925, 'en', 'They''re not too bad.')
               ,(1926, 'en', 'Hagh! They... certainly... more style... than yours.')
               ,(1927, 'en', 'Thanks... I... feel better.')
               ,(1928, 'en', 'Hoogh... You... should try... wearing them.')
               ,(1929, 'en', 'Maybe... compared to... goorgh... rest of life.')

               ,(1930, 'en', 'You... try on... then!')
               ,(1931, 'en', 'Uhn... You just... think you better... than me.')
               ,(1932, 'en', 'Ugh... You just... too lazy.')
               ,(1933, 'en', 'No... they''re... bad.... like me...')
           ,(1934, 'en', 'My hands are literal blocks.')
               ,(1935, 'en', '...Wow. Mine... too. Suh... Strange... isn''t it?')
               ,(1936, 'en', 'We... not so... different.')
               ,(1937, 'en', '...No kidding. Mine... too.')
               ,(1938, 'en', 'Gruh... At least... you can put down.')

               ,(1939, 'en', 'Well... done... Sherlock Bones...')
               ,(1940, 'en', '...You think... I stupid?')
               ,(1941, 'en', 'Argh... I... know. Don''t... care...')
               ,(1942, 'en', 'Murgh... Don''t... toy... with me.')
           ,(1943, 'en', 'I''m good when I''m paid.')
               ,(1944, 'en', 'Guess... you no take... rotten flesh?')
               ,(1945, 'en', 'I... gruh... think about it...')
               ,(1946, 'en', 'Harh... You... better be.')
               ,(1947, 'en', 'Hurh... Fair''s... fair.')

               ,(1948, 'en', 'With... that tatty shirt? I... see... this stitch up.')
               ,(1949, 'en', 'Hooh... Was hoping... kind.')
               ,(1950, 'en', 'I... not fall... for con.')
               ,(1951, 'en', 'You... greedy. That... lead you... to darkness... and demise.')


      ,(1952, 'en', 'Understand... you. Have %POWER% power.')
      ,(1953, 'en', 'We same... You take %POWER% power now.')
      ,(1954, 'en', 'Enjoy... life... with %POWER% power.')
      ,(1955, 'en', '%POWER% power... yours.')
;