INSERT INTO TextContent (TextContentId, BaseLanguageCode, BaseText)
VALUES
       (800, 'en', 'Destruction is what you ssseek? I thought humans were creatorsss?')
           ,(801, 'en', 'Figured I''d give it a go.')
               ,(802, 'en', 'It isss pretty fun.')
               ,(803, 'en', 'Sss-')
               ,(804, 'en', 'Predictable responsssse, but I like it.')
               ,(805, 'en', 'Sssome might find it fun...')

               ,(806, 'en', 'Ha. Sssee if you can top thisss.')
               ,(807, 'en', 'Sssorry, I can''t let you play around with it.')
               ,(808, 'en', 'Typical humansss. Enough of thisss!')
               ,(809, 'en', 'Sssigh. I can''t let you play with thisss.')
           ,(810, 'en', 'I need to prepare land for building.')
               ,(811, 'en', 'I could alwaysss do that for you, you know.')
               ,(812, 'en', 'Don''t make too much noissse with that.')
               ,(813, 'en', 'You humansss are never sssatisfied with nature. Curiousss.')
               ,(814, 'en', 'More of thisss world you humans are taking, then.')

               ,(815, 'en', 'Sssnore. You''re boring. Let''sss have sssome real fun.')
               ,(816, 'en', 'S- Ssstop! I like thisss place how it isss.')
               ,(817, 'en', 'I''ve had enough of you humansss wrecking thisss world.')
               ,(818, 'en', 'More conssstruction? I''m rather sssick of it I''m afraid.')
           ,(819, 'en', 'I''m no normal human.')
               ,(820, 'en', 'Sssorta look like one to me.')
               ,(821, 'en', 'So you''re sssome sort of sssuper human then? Hmm.')
               ,(822, 'en', 'I heard all humansss think that. Interesssting.')
               ,(823, 'en', 'I''m no ssstandard Creeper, too. We''re both outcastsss.')

               ,(824, 'en', 'Get off your high horssse.')
               ,(825, 'en', 'Are humansss... evolving? I''ve had enough change.')
               ,(826, 'en', 'Ssso they all sssay. You''re nothing ssspecial.')
               ,(827, 'en', 'Ssso what? Thisss is too much effort...')
      ,(828, 'en', 'Ssso, conversssely, have you ever heard of a Creeper that buildsss?')
          ,(829, 'en', 'Anyone can be a builder.')
               ,(830, 'en', 'Heh, sssuppose ssso.')
               ,(831, 'en', 'Maybe sssomeday...')
               ,(832, 'en', 'Sssounds daft...')
               ,(833, 'en', 'Sssometimes I think I might be able to...')

               ,(834, 'en', 'I''ll ssstick to blowing up. You.')
               ,(835, 'en', 'Wha- really? You''re jussst teasssing me, aren''t you? Fine.')
               ,(836, 'en', 'What a load of crap.')
               ,(837, 'en', 'Dreamsss for sssome. But not for me.')
          ,(838, 'en', 'How? You don''t have hands!')
               ,(839, 'en', 'Heh, that''sss a fair point.')
               ,(840, 'en', 'Sssuppose, no need to ssshout it about though.')
               ,(841, 'en', 'Ssstill could do better than humansss.')
               ,(842, 'en', 'Yeah, maybe it''sss a sssilly dream...')

               ,(843, 'en', 'Doesssn''t ssstop me from doing thisss!')
               ,(844, 'en', 'Ssso that''sss what it takes? I''ll ssstick to what I can do then...')
               ,(845, 'en', 'Neither will you!')
               ,(846, 'en', 'Ssso there''sss nothing to live for. Ssso be it.')
          ,(847, 'en', 'No.')
               ,(848, 'en', 'No beating around the busssh, then?')
               ,(849, 'en', 'Oh. Okay...')
               ,(850, 'en', 'Makes sssense.')
               ,(851, 'en', 'Ssshame. One can dream I sssuppose.')

               ,(852, 'en', 'It wasss a joke. I''ll give you sssomething ssserious to think about.')
               ,(853, 'en', 'Ssso rude!')
               ,(854, 'en', 'Try sssome kindnesss next time.')
               ,(855, 'en', 'Could''ve usssed the uplift, you know?')
      ,(856, 'en', 'At any rate, you ssseek my power due to your human weaknessss?')
           ,(857, 'en', 'Shuddup...')
               ,(858, 'en', 'Ha, I''ll think about it.')
               ,(859, 'en', 'I ssshould sssay the sssame to you!')
               ,(860, 'en', 'Sssassy one, aren''t we?')
               ,(861, 'en', 'Did I ssstrike a cord?')

               ,(862, 'en', 'I''ll ssshut you up.')
               ,(863, 'en', 'I''ll sssshut up in the after life.')
               ,(864, 'en', 'We''ll sssee who ssshuts up first.')
               ,(865, 'en', 'Ssso be it.')
           ,(866, 'en', 'Humans are still stronger than Creepers!')
               ,(867, 'en', 'I''ll let you think that. Haha.')
               ,(868, 'en', 'Maybe ssso...')
               ,(869, 'en', 'Maybe sssome of you can be.')
               ,(870, 'en', 'Maybe jussst me, I''ll give you that.')

               ,(871, 'en', 'Want to put that to the tessst? Let''s go.')
               ,(872, 'en', 'Arroganccce won''t serve you.')
               ,(873, 'en', 'Then let''sss sssee where your power gets you.')
               ,(874, 'en', 'I can ssstill pack sssome trouble. Just watch.')
           ,(875, 'en', 'I have my reasons...')
               ,(876, 'en', 'Ah, too ssscared to admit it. I get it.')
               ,(877, 'en', 'Asss do I...')
               ,(878, 'en', 'Fair enough.')
               ,(879, 'en', 'Heh, don''t we all?')

               ,(880, 'en', 'Not going to ssshare? Very well. Let''sss sssee if you ssshare in the after life.')
               ,(881, 'en', 'Then you''ll have to excussse mine. I can''t take speechesss.')
               ,(882, 'en', 'And I jussst found a reassson to blow you up.')
               ,(883, 'en', 'And you don''t trussst me to keep them sssecret? Very well.')




      ,(884, 'en', 'My power? Why? You''ve already hit me hard...')
           ,(885, 'en', 'Sorry...')
               ,(886, 'en', 'Heh, don''t worry about it.')
               ,(887, 'en', 'No worriesss...')
               ,(888, 'en', 'Finally, sssome mannersss.')
               ,(889, 'en', 'You don''t need to feel sssorry for me.')

               ,(890, 'en', 'I''ll make you sssorry.')
               ,(891, 'en', 'I''m sssorry for thisss...')
               ,(892, 'en', 'Apology denied.')
               ,(893, 'en', 'Don''t wassste your sssympathy on me.')
           ,(894, 'en', 'It sounded like you enjoyed it.')
               ,(895, 'en', 'Maybe I did.')
               ,(896, 'en', 'I have my interestsss...')
               ,(897, 'en', 'Tsss...')
               ,(898, 'en', 'The pain remindsss me I''m alive.')

               ,(899, 'en', 'I''ll ssshow you sssomething I enjoy.')
               ,(900, 'en', 'Not ssso much...')
               ,(901, 'en', 'No.')
               ,(902, 'en', 'I have no joysss.')
           ,(903, 'en', 'It''s my only use for you.')
               ,(904, 'en', 'At leassst I have a ussse.')
               ,(905, 'en', 'Very well...')
               ,(906, 'en', 'Fair enough.')
               ,(907, 'en', 'Yeah...')

               ,(908, 'en', 'And I have none for you.')
               ,(909, 'en', 'I don''t think ssso...')
               ,(910, 'en', 'I have none for you.')
               ,(911, 'en', 'I have no ussse.')
      ,(912, 'en', 'Ssstill, it hurts...')
           ,(913, 'en', 'I really am sorry...')
               ,(914, 'en', 'Yeah, I get it.')
               ,(915, 'en', 'Thanksss. That makesss it a little better.')
               ,(916, 'en', 'Underssstood.')
               ,(917, 'en', 'You sssound sssincere...')

               ,(918, 'en', 'Let me cheer you up.')
               ,(919, 'en', 'That''sss not enough...')
               ,(920, 'en', 'Ssorrysss can''t be usssed as bandagessss!')
               ,(921, 'en', 'I have a sssorry life...')
           ,(922, 'en', 'Toughen up.')
               ,(923, 'en', 'Sssame to you.')
               ,(924, 'en', 'I ssshould...')
               ,(925, 'en', 'Point taken.')
               ,(926, 'en', 'Hmm...')

               ,(927, 'en', 'My ssspirit''s tough. I''ll ssshow you.')
               ,(928, 'en', 'That''sss not me.')
               ,(929, 'en', 'Why don''t you?')
               ,(930, 'en', 'I''m not interesssted.')
           ,(931, 'en', 'I''ll kiss it better.')
               ,(932, 'en', 'Come lean in then.')
               ,(933, 'en', 'You think that''ll work?')
               ,(934, 'en', 'You mussst have a magic touch.')
               ,(935, 'en', 'I''ll try anything...')

               ,(936, 'en', 'Come here. I''ll kissss you.')
               ,(937, 'en', 'Don''t patronisssse me.')
               ,(938, 'en', 'Don''t even try.')
               ,(939, 'en', 'Isss that sssupposed to be a joke?')
      ,(940, 'en', 'Talking it out, I''m ssstarting to feel better.')
           ,(941, 'en', 'Good to hear.')
               ,(942, 'en', 'Yeah, it isss.')
               ,(943, 'en', 'Thanksss for ssstaying with me.')
               ,(944, 'en', 'It isss...')
               ,(945, 'en', 'I think ssso...')

               ,(946, 'en', 'It isss. Now I can beat you.')
               ,(947, 'en', 'Thanksss... but I need to protect myssself.')
               ,(948, 'en', 'Don''t lie.')
               ,(949, 'en', 'Isss that truly have you feel?')
           ,(950, 'en', 'We can''t be having that.')
               ,(951, 'en', 'Then let''sss wrap thisss up.')
               ,(952, 'en', 'Hold on...')
               ,(953, 'en', 'Yesss, we can.')
               ,(954, 'en', 'C''mon, give me thisss.')

               ,(955, 'en', 'I think we can.')
               ,(956, 'en', 'We... can''t?')
               ,(957, 'en', 'I dissssagree.')
               ,(958, 'en', 'Maybe not... Let''sss battle it to the death.')
           ,(959, 'en', 'That''s my ''power''.')
               ,(960, 'en', 'I sssee why you need mine inssstead.')
               ,(961, 'en', 'I like it.')
               ,(962, 'en', 'That mussst come in helpful.')
               ,(963, 'en', 'I wisssh I had that power...')

               ,(964, 'en', 'What a ssstupid power. Here''sss mine!')
               ,(965, 'en', 'I... need it.')
               ,(966, 'en', 'Don''t lie to me.')
               ,(967, 'en', 'Don''t bother wasssting it on me.')





      ,(968, 'en', 'More humansss after my power? Ugh, why do I always find myssself in thisss sssorry ssstate?')
           ,(969, 'en', 'Because you''re special.')
               ,(970, 'en', 'Don''t I know it?')
               ,(971, 'en', 'You think ssso?')
               ,(972, 'en', 'Thanksss, but I don''t think ssso.')
               ,(973, 'en', 'Heh... Maybe...')

               ,(974, 'en', 'That''sss just not me.')
               ,(975, 'en', 'I''m just an ordinary Creeper. I have nothing to offer you.')
               ,(976, 'en', 'None of usss are ssspecial.')
               ,(977, 'en', 'No, I don''t think ssso...')
           ,(978, 'en', 'Because you''re weak.')
               ,(979, 'en', 'Maybe I am, never could find a good bassse to blow up.')
               ,(980, 'en', 'Yeah...')
               ,(981, 'en', 'Heh, you sssay it how it isss.')
               ,(982, 'en', 'I know, I know.')

               ,(983, 'en', 'That''sss not very nice. I''ll have to blow you up twice!')
               ,(984, 'en', 'I can''t take any more of this...')
               ,(985, 'en', 'You have no right to sssay that.')
               ,(986, 'en', 'I didn''t need to hear that from you.')
           ,(987, 'en', 'Because it''s fate.')
               ,(988, 'en', 'Heh, if you believe in all that I''ll play along.')
               ,(989, 'en', 'I''ve never consssidered I have a fate.')
               ,(990, 'en', 'Never cared much for fate, but it''sss certainly not my fault.')
               ,(991, 'en', 'Hey, maybe you''re right...')

               ,(992, 'en', 'You sssound ridiculousss.')
               ,(993, 'en', 'I don''t have one.')
               ,(994, 'en', 'Abssssolute nonsenssse.')
               ,(995, 'en', 'Fate isss for foolsss.')
      ,(996, 'en', 'I wonder, if I were human, would thingsss be different?')
           ,(997, 'en', 'Who knows?')
               ,(998, 'en', 'I think I have a clue.')
               ,(999, 'en', 'Sssomebody sssmarter than me, maybe.')
               ,(1000, 'en', 'I do.')
               ,(1001, 'en', 'Maybe we''ll never know.')

               ,(1002, 'en', 'It''sss anyone''sss guess.')
               ,(1003, 'en', 'Guesss I''ll never know...')
               ,(1004, 'en', 'Sssounds like you don''t care.')
               ,(1005, 'en', 'I''ll never find out...')
           ,(1006, 'en', 'That''s impossible.')
               ,(1007, 'en', 'I can alwaysss dream.')
               ,(1008, 'en', 'I sssuppose being a Creeper isssn''t ssso bad, really.')
               ,(1009, 'en', 'That''sss true. No point dwelling on it.')
               ,(1010, 'en', 'Grim timesss, hey?')

               ,(1011, 'en', 'They sssaid the sssame thing about a creature that EXPLODESSS!')
               ,(1012, 'en', 'I guesss so...')
               ,(1013, 'en', 'Obviousssly.')
               ,(1014, 'en', 'Ssso much for my dreamsss.')
           ,(1015, 'en', 'You''d blow up less.')
               ,(1016, 'en', 'I''ve ssseen you humansss play with TNT, you know?')
               ,(1017, 'en', 'I''d like that.')
               ,(1018, 'en', 'Sssounds like an excellent perk.')
               ,(1019, 'en', 'That sssounds nice for you.')

               ,(1020, 'en', 'That''sss not the life for me.')
               ,(1021, 'en', 'That''sss too different for me.')
               ,(1022, 'en', 'Real jokessster you are.')
               ,(1023, 'en', 'I prefer the easssy out.')
      ,(1024, 'en', 'Tell me, do you ever find yourself in the sssame sssituation?')
           ,(1025, 'en', 'That''s a secret.')
               ,(1026, 'en', 'C''mon, you can tell me.')
               ,(1027, 'en', 'I ssseee.')
               ,(1028, 'en', 'We all have our sssecrets.')
               ,(1029, 'en', 'I get that. Yoursss isss probably better than mine. Thanksss for not bragging.')

               ,(1030, 'en', 'Don''t you trussst me?')
               ,(1031, 'en', 'Do you not like me enough to ssshare?')
               ,(1032, 'en', 'It wasss a sssimple quessstion.')
               ,(1033, 'en', 'Eh, doesssn''t matter anyway...')
           ,(1034, 'en', 'I''m too cool to get caught.')
               ,(1035, 'en', 'Ssssure you are.')
               ,(1036, 'en', 'I wisssh I could be that cool...')
               ,(1037, 'en', 'Careful with that confidenccce.')
               ,(1038, 'en', 'I usssed to think the sssame...')

               ,(1039, 'en', 'But not asss cool asss me.')
               ,(1040, 'en', 'You ssshouldn''t talk to me, then...')
               ,(1041, 'en', 'Arroganccce will get you nowhere.')
               ,(1042, 'en', 'I can''t ssstand your attitude.')
           ,(1043, 'en', 'All the time.')
               ,(1044, 'en', 'Honesssty is the bessst policy!')
               ,(1045, 'en', 'We have that in common.')
               ,(1046, 'en', 'It''sss irritating, right?')
               ,(1047, 'en', 'That mussst sssuck. Trussst me, I''d know.')

               ,(1048, 'en', 'Sssucks to be you.')
               ,(1049, 'en', 'You sssound like you can take it, though...')
               ,(1050, 'en', 'Don''t lie.')
               ,(1051, 'en', 'You''re worssse than me.')


      ,(1052, 'en', 'I had fun. Here, enjoy thisss %POWER% power.')
      ,(1053, 'en', 'Thanksss for the chat. Here, take thisss power of %POWER%.')
      ,(1054, 'en', 'Well, that''sss my time. Thanksss. Take thisss %POWER% power.')
      ,(1055, 'en', 'Hey, it wasssn''t bad to chat. Thanksss. Take thisss power of %POWER%.')
;