INSERT INTO TextContent (TextContentId, BaseLanguageCode, BaseText)
VALUES
       (1400, 'en', 'The spider doesn''t seem to understand...')
           ,(1401, 'en', 'Say it again, but louder.')
               ,(1402, 'en', 'The spider appears to be chuckling back at you...')
               ,(1403, 'en', 'You got the spider''s attention!')
               ,(1404, 'en', 'The spider appears to be... bowing?')
               ,(1405, 'en', 'The spider shows some signs of attention...')

               ,(1406, 'en', 'The spider noisily leaps out!')
               ,(1407, 'en', 'The spider''s become defensive!')
               ,(1408, 'en', 'The spider''s loudly readying an attack!')
               ,(1409, 'en', 'The spider''s groaning with a deadly stare!')
           ,(1410, 'en', 'Say it again, but slower.')
               ,(1411, 'en', 'The spider''s started moving in slow motion. It appears to be mocking you.')
               ,(1412, 'en', 'The spider seems to be understanding a little better now?')
               ,(1413, 'en', '...')
               ,(1414, 'en', 'The spider seems a little more interested now.')

               ,(1415, 'en', 'The spider excitedly leaps out at speed!')
               ,(1416, 'en', 'The spider''s become defensive!')
               ,(1417, 'en', 'The spider looks to be readying an attack and definitely not slowly!')
               ,(1418, 'en', 'It''s no use. The spider isn''t responding!')
           ,(1419, 'en', 'Wait.')
               ,(1420, 'en', 'The spider seems to have taken that as some sort of game.')
               ,(1421, 'en', 'The spider remains silent...')
               ,(1422, 'en', 'The spider seems to be waiting for you...')
               ,(1423, 'en', 'The spider remains silent...')

               ,(1424, 'en', 'The spider looks to have become bored. It''s looking for other entertainment!')
               ,(1425, 'en', 'The spider''s become cynical of you!')
               ,(1426, 'en', 'The spider''s patience has worn thin! It''s become aggressive!')
               ,(1427, 'en', 'The spider''s giving you an unnerving glare...')
      ,(1428, 'en', 'It seems to be eyeing up your inventory...')
          ,(1429, 'en', 'Eye it back.')
               ,(1430, 'en', 'The spider''s starting a staring competition!')
               ,(1431, 'en', 'The spider is easing off...)
               ,(1432, 'en', '...Neither of you are breaking down.')
               ,(1433, 'en', 'The spider is gradually drifting its eyes away.')

               ,(1434, 'en', 'The spider''s gaze has turned to you and become more deadly!')
               ,(1435, 'en', 'The spider seems to now be considering something more nefarious!')
               ,(1436, 'en', 'The spider''s become agitated!')
               ,(1437, 'en', 'The spider seems to have given up talking!')
          ,(1438, 'en', 'Pretend to offer something.')
               ,(1439, 'en', 'Seems the spider knows that''s the oldest trick in the book! It''s smirking!')
               ,(1440, 'en', 'Got ''em! The spider seems ashamed to have fallen for that.')
               ,(1441, 'en', '...')
               ,(1442, 'en', 'It didn''t even bother looking up to notice...')

               ,(1443, 'en', 'Bad idea! The spider looks like it''s about to play its own trick!')
               ,(1444, 'en', 'The spider''s shying away...')
               ,(1445, 'en', 'Now it''s irritated!')
               ,(1446, 'en', 'It doesn''t seem amused...')
          ,(1447, 'en', 'Shake your head.')
               ,(1448, 'en', 'The spider nods back.')
               ,(1449, 'en', 'It seems rather dismayed by your response...')
               ,(1450, 'en', 'The spider has retracted its attention.')
               ,(1451, 'en', 'It seems rather dismayed by your response...')

               ,(1452, 'en', 'The spider''s shaking something up! It''s readying to attack!')
               ,(1453, 'en', 'It''s lost interest in negotiation!')
               ,(1454, 'en', 'That''s riled it up!')
               ,(1455, 'en', 'It''s lost the will to continue on!')
      ,(1456, 'en', 'It appears to be deep in thought...')
           ,(1457, 'en', 'Say it again.')
               ,(1458, 'en', 'Oddly enough, it still doesn''t seem to understand.')
               ,(1459, 'en', 'The spider appears concerned about your repetitive nature.')
               ,(1460, 'en', '...')
               ,(1461, 'en', 'The look it''s giving you... The spider may be starting to take you for a parrot.')

               ,(1462, 'en', 'That''s done it! It''s had enough fun and games!')
               ,(1463, 'en', 'The spider hasn''t taken kindly to that!')
               ,(1464, 'en', 'Once might''ve been enough! Now you''re in trouble!')
               ,(1465, 'en', 'It doesn''t seem to have much hope for your intellect...')
           ,(1466, 'en', 'Pull a pose like The Thinker.')
               ,(1467, 'en', 'That seems to have humoured it. It seems friendlier now!')
               ,(1468, 'en', 'The spider seems to genuinely think you''re in deep thought...')
               ,(1469, 'en', 'The spider gives you a nod.')
               ,(1470, 'en', 'It seems more at ease now.')

               ,(1471, 'en', 'There''s no denying the face it''s giving you - It thinks you look ridiculous!')
               ,(1472, 'en', 'It hasn''t taken well to being mocked!')
               ,(1473, 'en', 'Looks like it doesn''t have time for tomfoolery!')
               ,(1474, 'en', 'That''s set it off!')
           ,(1475, 'en', 'Whistle a tune while waiting.')
               ,(1476, 'en', 'It''s getting its boogie on!')
               ,(1477, 'en', 'It seems like it wants to learn this tune...')
               ,(1478, 'en', 'Whistling a calming tune seems to have appeased it.')
               ,(1479, 'en', 'Whistling a gloomy tune, it seems to relate.')

               ,(1480, 'en', 'Looks like it''s not a fan!')
               ,(1481, 'en', 'It seems to prefer silence!')
               ,(1482, 'en', 'It''s lost its train of thought - Now it''s mad!')
               ,(1483, 'en', 'No bueno. That''s irritated it!')







      ,(1484, 'en', 'The spider seems disinterested...')
           ,(1485, 'en', 'Snap your fingers at it.')
               ,(1486, 'en', 'It''s got its eyes on you now!')
               ,(1487, 'en', 'It''s looking up with fear in its eyes.')
               ,(1488, 'en', 'You''ve got its full attention with that!')
               ,(1489, 'en', 'It''s giving you a look... But at least it''s paying attention.')

               ,(1490, 'en', 'It''s snapping back!')
               ,(1491, 'en', 'It hasn''t responded well to hostility!')
               ,(1492, 'en', 'That enraged it!')
               ,(1493, 'en', 'It''s turned on you!')
           ,(1494, 'en', 'Tell it a fairy-tale.')
               ,(1495, 'en', 'It seems to have enjoyed that.')
               ,(1496, 'en', 'It looks like it''s taken the message of the story to heart... Somehow.')
               ,(1497, 'en', 'Its eyes are on you now. It might be waiting for another.')
               ,(1498, 'en', 'It quietly listened. Seems you have its attention.')

               ,(1499, 'en', 'Doesn''t look like it''s a fan of the classics!')
               ,(1500, 'en', 'It hasn''t taken the moral of the story to heart!')
               ,(1501, 'en', 'No good. It''s at a higher reading level.')
               ,(1502, 'en', 'It doesn''t appear to appreciate the happy ending.')
           ,(1503, 'en', 'Stare into its deep beautiful eyes...')
               ,(1504, 'en', 'As your eyes lock, you lean in for a kiss... Eurgh. No. It''s a spider. Enough of that. At least that''s garnered some attention...')
               ,(1505, 'en', 'It''s blushing...')
               ,(1506, 'en', 'It''s certainly more engaged now, and perhaps a little attracted...')
               ,(1507, 'en', 'It''s staring back, right into your very soul, with a longing for love in it''s 8 sparkling peepers.')

               ,(1508, 'en', 'The eyes are looking a little angrier now. Here it comes!')
               ,(1509, 'en', 'That seems to have made it uncomfortable...')
               ,(1510, 'en', 'It hasn''t got time for that. Watch out!')
               ,(1511, 'en', 'It doesn''t appear to be in the mood...')
      ,(1512, 'en', 'The spider is beckoning you closer...')
           ,(1513, 'en', 'Go closer.')
               ,(1514, 'en', 'The spider seems elated! It''s sniffing you up.')
               ,(1515, 'en', 'It''s become more at ease.')
               ,(1516, 'en', 'Your prompt response seems to have appeased it!')
               ,(1517, 'en', 'Its demeanour seems to be slightly happier to have you close.')

               ,(1518, 'en', 'It was a trick! Watch out!')
               ,(1519, 'en', 'Too close! It''s retaliating!')
               ,(1520, 'en', 'It was a revenge trick! Watch out!')
               ,(1521, 'en', 'Looks like it wanted you to come closer for a fight!')
           ,(1522, 'en', 'Stay back.')
               ,(1523, 'en', 'It''s slowly inching towards you instead!')
               ,(1524, 'en', 'It seems to relate to your shyness.')
               ,(1525, 'en', 'The spider seems to respect your determined stance!')
               ,(1526, 'en', 'Your decision has sent the spider into deep thought...')

               ,(1527, 'en', 'Not one for a stand-off it seems! Here it comes!')
               ,(1528, 'en', 'It doesn''t seem to trust you anymore!')
               ,(1529, 'en', 'It''s grown impatient! Watch out!')
               ,(1530, 'en', 'It didn''t appreciate your hesitation.')
           ,(1531, 'en', 'Gesture back.')
               ,(1532, 'en', 'It''s coming over, with a skip in its step!')
               ,(1533, 'en', 'It''s approaching cautiously...')
               ,(1534, 'en', 'It''s coming over, though seems to have a bit of a huff on!')
               ,(1535, 'en', 'It appears curious as it slogs its way over.')

               ,(1536, 'en', 'It''s charging over!!!')
               ,(1537, 'en', 'It seems to suspect you''re up to something. Watch out!')
               ,(1538, 'en', 'It''s not having any of that!')
               ,(1539, 'en', 'It can''t be bothered. It''s grown more hostile.')
      ,(1540, 'en', 'It''s looking at you expectantly...')
           ,(1541, 'en', 'Show off your loot.')
               ,(1542, 'en', 'The spider seems curious about your items.')
               ,(1543, 'en', 'It''s inspecting your items with awe.')
               ,(1544, 'en', 'It appears to be quite impressed!')
               ,(1545, 'en', 'It seems perplexed by your treasures...')

               ,(1546, 'en', 'It doesn''t look too impressed!')
               ,(1547, 'en', 'It doesn''t agree with your wealth!')
               ,(1548, 'en', 'It hasn''t taken well to your showing off!')
               ,(1549, 'en', 'It''s become rather bored...')
           ,(1550, 'en', 'Bust a move.')
               ,(1551, 'en', 'It''s joined in a synchronised dance!')
               ,(1552, 'en', 'It appears rather impressed!')
               ,(1553, 'en', 'It seems to appreciate your skill.')
               ,(1554, 'en', 'It looks to be reading into your dance...')

               ,(1555, 'en', 'It was a ruse! It''s laughing at you!')
               ,(1556, 'en', 'It''s intimidated by your raw skill. It knows it could never match up...')
               ,(1557, 'en', 'It doesn''t appear to be a fan of that favour of dance...')
               ,(1558, 'en', 'It doesn''t seem keen on the mainstream dance style...')
           ,(1559, 'en', 'Enlighten it with knowledge.')
               ,(1560, 'en', 'It appears flabbergasted by this new revelation!')
               ,(1561, 'en', 'It''s carefully reflecting on this new knowledge...')
               ,(1562, 'en', 'It seems to appreciate your teachings.')
               ,(1563, 'en', 'It appears to be pondering over the meaning of life...')

               ,(1564, 'en', 'You''ve bored it!')
               ,(1565, 'en', 'It feels stupid...')
               ,(1566, 'en', 'It''s offended by the simplicity of your teachings.')
               ,(1567, 'en', 'It appears disinterested.')





      ,(1568, 'en', 'The spider is trying to get away...')
           ,(1569, 'en', 'Stop it.')
               ,(1570, 'en', 'You successfully held it back!')
               ,(1571, 'en', 'You managed to keep it around!')
               ,(1572, 'en', 'The spider appears to respect your might and remains.')
               ,(1573, 'en', 'The spider is curious of your intentions...')

               ,(1574, 'en', 'No use! It''s too fast!')
               ,(1575, 'en', 'No use! It''s scuttled away in fear!')
               ,(1576, 'en', 'No use! It''s determined to shoot off!')
               ,(1577, 'en', 'No use! It''s evading all attempts with reckless abandon!')
           ,(1578, 'en', 'Let it leave.')
               ,(1579, 'en', 'It''s circled back around! It might''ve wanted to play chase.')
               ,(1580, 'en', 'The spider stuck around after your kindness, it doesn''t appear so intimidated anymore.')
               ,(1581, 'en', '...')
               ,(1582, 'en', 'It seems curious as to why you would let it get away...')

               ,(1583, 'en', 'It''s turned back with aggression!')
               ,(1584, 'en', 'Gah! It was a trick to strike back!')
               ,(1585, 'en', 'It was distancing for an attack!')
               ,(1586, 'en', 'It''s returning the favour, and not in a good way!')
           ,(1587, 'en', 'Plead for it to stay.')
               ,(1588, 'en', 'It seems humoured by your weakness and has stuck around.')
               ,(1589, 'en', 'It''s staying around to relieve you of your turmoil...')
               ,(1590, 'en', 'It seems to appreciate your honesty and has stuck around.')
               ,(1591, 'en', 'It''s struck by your unusual behaviour!')

               ,(1592, 'en', 'It''s taken that as a sign of weakness!')
               ,(1593, 'en', 'It''s ineffective!')
               ,(1594, 'en', 'It''s annoyed by your blubbering. Watch out!')
               ,(1595, 'en', 'It seems disinterested in your plea.')
      ,(1596, 'en', 'It looks like it might want to join you on your adventures...')
           ,(1597, 'en', 'Gently let it down.')
               ,(1598, 'en', 'It seems relatively unfazed!')
               ,(1599, 'en', 'It seems to have appreciated the soft response!')
               ,(1600, 'en', 'It seems to understand.')
               ,(1601, 'en', 'It appears disappointed, but understanding.')

               ,(1602, 'en', 'It hasn''t taken that well!')
               ,(1603, 'en', 'That''s upset it!')
               ,(1604, 'en', 'That''s offended it!')
               ,(1605, 'en', 'It''s consumed with despair!')
           ,(1606, 'en', 'Reject it.')
               ,(1607, 'en', 'It''s acting like it wasn''t serious anyway! There''s no way of telling if it was or not...')
               ,(1608, 'en', '...')
               ,(1609, 'en', 'It seems appeased by your direct nature!')
               ,(1610, 'en', 'Looks like it was anticipating that response...')

               ,(1611, 'en', 'It''s ready to send you to the reject pile! Watch out!')
               ,(1612, 'en', 'That''s shaken it to the core!')
               ,(1613, 'en', 'It doesn''t appear to appreciate your tone.')
               ,(1614, 'en', 'It''s now longing for something more... deadly.')
           ,(1615, 'en', 'Explain that you work alone.')
               ,(1616, 'en', 'It''s humoured by your attempt to look cool!')
               ,(1617, 'en', 'It seems to understand...')
               ,(1618, 'en', 'It''s impressed!')
               ,(1619, 'en', 'It appears to relate to the sombre lifestyle...')

               ,(1620, 'en', 'It hasn''t taken that well!')
               ,(1621, 'en', 'That''s upset it!')
               ,(1622, 'en', 'That''s offended it!')
               ,(1623, 'en', 'It''s consumed with despair!')
      ,(1624, 'en', 'It seems curious about who you are...')
           ,(1625, 'en', 'Tell it that''s secret.')
               ,(1626, 'en', 'It seems pretty confident it can sniff you out.')
               ,(1627, 'en', 'It appears enamoured with your mysterious persona!')
               ,(1628, 'en', 'It seems a little antsy about not knowing.')
               ,(1629, 'en', 'It too seems to be harbouring secrets...')

               ,(1630, 'en', 'Looks like it''s tired of playing "Guess Who?"!')
               ,(1631, 'en', 'That seems to have destroyed any trust it had!')
               ,(1632, 'en', 'Seems it''s not keen on not knowing!')
               ,(1633, 'en', 'It can sense your weak attempt to be honest edgy.')
           ,(1634, 'en', 'Tell it you''re a fancy banker.')
               ,(1635, 'en', 'Looks like you may have just set yourself up as the Monopoly banker for Spider Games night next week.')
               ,(1636, 'en', 'It seems to appreciate your supposed honesty... Better not tell it too much more.')
               ,(1637, 'en', 'It... Looks like it wants financial advice?')
               ,(1638, 'en', 'It''s dreaming about such a life for itself...')

               ,(1639, 'en', 'Nope. It''s not buying that.')
               ,(1640, 'en', 'It appears to be offended that you would think it so gullible.')
               ,(1641, 'en', 'It''s not taken well to your joking around!')
               ,(1642, 'en', 'It seems a little too down on how its life turned out... Be careful!')
           ,(1643, 'en', 'Tell it your life story.')
               ,(1644, 'en', 'It seems to have really enjoyed the parts where you failed.')
               ,(1645, 'en', 'Understanding you better, it seems closer now.')
               ,(1646, 'en', 'It''s listening intently - Seems honesty is the best policy!')
               ,(1647, 'en', 'It''s enamoured by your story...')

               ,(1648, 'en', 'You''ve bored it into madness! Watch out!')
               ,(1649, 'en', 'It''s edging away, feeling I sufficient against your achievements.')
               ,(1650, 'en', 'Your over-answering has really rather irritated it.')
               ,(1651, 'en', 'It''s become disinterested...')


      ,(1652, 'en', 'The spider shoots off with a spring in its step as it leaves behind its %POWER% power.')
      ,(1653, 'en', 'The spider takes its leave, rushing for solace, as it leaves behind its %POWER% power.')
      ,(1654, 'en', 'The spider scurries off, leaving behind its %POWER% power.')
      ,(1655, 'en', 'The spider slowly crawls off as it drops behind its %POWER% power.')
;